"""initial schema: users and saved_reviews tables

Revision ID: 3015d61a4208
Revises: 
Create Date: 2026-04-16 19:22:53.365777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3015d61a4208'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('saved_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('input_abstracts_count', sa.Integer(), nullable=False),
    sa.Column('extractive_summary', sa.Text(), nullable=True),
    sa.Column('abstractive_summary', sa.Text(), nullable=True),
    sa.Column('key_themes', sa.JSON(), nullable=True),
    sa.Column('visualizations_metadata', sa.JSON(), nullable=True),
    sa.Column('rouge_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saved_reviews_created_at', 'saved_reviews', ['created_at'], unique=False)
    op.create_index('idx_saved_reviews_user_id', 'saved_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_reviews_user_id'), 'saved_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_reviews_user_id'), table_name='saved_reviews')
    op.drop_index('idx_saved_reviews_user_id', table_name='saved_reviews')
    op.drop_index('idx_saved_reviews_created_at', table_name='saved_reviews')
    op.drop_table('saved_reviews')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
