// frontend/src/pages/ResultsPage.tsx
import { useState, useEffect } from 'react';
import { Copy, Check, Download, FileText } from 'lucide-react';
import { toast } from 'sonner';
import type { ProcessResponse } from '../types';
import { extractThemes } from '../lib/api';

interface ResultsPageProps {
  data: ProcessResponse | null;
  onBack: () => void;
  onSaveReview: () => void;
  onGoToMyReviews: () => void;
  reviewTitle: string;
  setReviewTitle: (title: string) => void;
}


// Utility function to calculate mock ROUGE scores
const calculateMetrics = (summary: string, sentences: number) => {
  const words = summary.split(/\s+/).length;
  
  // Mock ROUGE scores (in real scenario, these come from backend)
  return {
    rouge1: (0.65 + Math.random() * 0.25).toFixed(3),
    rouge2: (0.45 + Math.random() * 0.25).toFixed(3),
    rougeL: (0.60 + Math.random() * 0.25).toFixed(3),
    summaryLength: words,
    extractedSentences: sentences,
    compressionRatio: ((1 - words / (sentences * 25)) * 100).toFixed(1)
  };
};

// Utility function to export all results as text
const exportAsText = (filename: string, summary: string, sentences: any[]) => {
  const content = `
LITERATURE REVIEW EXPORT
=======================
Document: ${filename}
Exported: ${new Date().toLocaleString()}

ABSTRACTIVE SUMMARY (BART)
--------------------------
${summary}

KEY SENTENCES (TextRank)
------------------------
${sentences.map((s, i) => `${i + 1}. ${s.sentence}\n   Score: ${s.score.toFixed(3)}`).join('\n\n')}

---
Generated by Automated Literature Review Assistant
`;
  
  const element = document.createElement('a');
  element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
  element.setAttribute('download', `${filename.replace(/\.[^/.]+$/, '')}_review.txt`);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

// Utility function to export as PDF (using browser print)
const exportAsPDF = (filename: string) => {
  const printWindow = window.open('', '', 'height=600,width=800');
  if (printWindow) {
    const content = document.querySelector(`[data-export="${filename}"]`)?.innerHTML || '';
    printWindow.document.write(`
      <html>
        <head>
          <title>${filename} - Literature Review</title>
          <style>
            body { font-family: Arial, sans-serif; color: #333; margin: 40px; }
            h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
            h2 { color: #0f766e; margin-top: 30px; }
            .summary { background: #f0fdf4; padding: 15px; border-radius: 8px; margin: 20px 0; }
            .sentence { background: #f3f4f6; padding: 12px; margin: 10px 0; border-left: 4px solid #0d9488; }
            .metrics { background: #f9fafb; padding: 15px; border-radius: 8px; margin: 20px 0; }
            .metric-item { display: inline-block; margin-right: 20px; }
            .footer { margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
          </style>
        </head>
        <body>
          ${content}
          <div class="footer">
            Generated by Automated Literature Review Assistant • Hybrid TextRank + BART Pipeline
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }
};

export default function ResultsPage({ 
  data, 
  onBack, 
  onSaveReview,
  onGoToMyReviews,
  reviewTitle, 
  setReviewTitle 
}: ResultsPageProps) {
  
  const [activeTabs, setActiveTabs] = useState<Record<string, 'summary' | 'extractive'>>({});
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [themesData, setThemesData] = useState<Record<string, string[]>>({});
  const [loadingThemes, setLoadingThemes] = useState<Record<string, boolean>>({});

  // Fetch themes for all results when data changes
  useEffect(() => {
    if (!data) return;

    const fetchAllThemes = async () => {
      const themesMap: Record<string, string[]> = {};
      
      for (const result of data.results) {
        if (!result.abstractive_summary) {
          themesMap[result.filename] = [];
          continue;
        }

        try {
          setLoadingThemes(prev => ({ ...prev, [result.filename]: true }));
          const themes = await extractThemes(result.abstractive_summary);
          themesMap[result.filename] = themes;
        } catch (error) {
          console.error(`Failed to extract themes for ${result.filename}:`, error);
          // Gracefully fail - show empty themes instead of blocking
          themesMap[result.filename] = [];
        } finally {
          setLoadingThemes(prev => ({ ...prev, [result.filename]: false }));
        }
      }

      setThemesData(themesMap);
    };

    fetchAllThemes();
  }, [data]);

  if (!data) {
    return <div className="text-center py-20 text-gray-400">No results available</div>;
  }

  const copyToClipboard = async (text: string, id: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(id);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopiedId(null), 2000);
    } catch (err) {
      toast.error('Failed to copy to clipboard');
    }
  };

  // Copy all results for current paper
  const copyAllResults = (result: any) => {
    const allText = `
SUMMARY:
${result.abstractive_summary}

KEY SENTENCES:
${result.extractive?.key_sentences?.map((s: any) => s.sentence).join('\n\n')}
    `.trim();
    copyToClipboard(allText, `all-${result.filename}`);
  };

  const getActiveTab = (filename: string) => activeTabs[filename] || 'summary';

  const setActiveTab = (filename: string, tab: 'summary' | 'extractive') => {
    setActiveTabs(prev => ({ ...prev, [filename]: tab }));
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white pb-12">
      {/* Header */}
      <div className="border-b border-gray-800 bg-gray-900">
        <div className="max-w-full md:max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-4 sm:py-6 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 sm:gap-0">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">Literature Review Results</h1>
            <p className="text-gray-400 text-sm sm:text-base">
              Processed {data.processed_files} document{data.processed_files !== 1 ? 's' : ''}
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 w-full sm:w-auto">
            <button
              onClick={onBack}
              className="px-3 sm:px-6 py-2 sm:py-3 border border-gray-700 hover:bg-gray-800 rounded-xl transition text-sm sm:text-base whitespace-nowrap"
            >
              ← Back to Upload
            </button>
            <button
              onClick={onGoToMyReviews}
              className="px-3 sm:px-6 py-2 sm:py-3 border border-gray-700 hover:bg-gray-800 rounded-xl transition text-sm sm:text-base whitespace-nowrap"
            >
              My Reviews
            </button>
            <button
              onClick={onSaveReview}
              disabled={!reviewTitle.trim()}
              className="px-3 sm:px-6 py-2 sm:py-3 bg-teal-600 hover:bg-teal-500 disabled:bg-gray-700 rounded-xl transition text-sm sm:text-base whitespace-nowrap"
            >
              Save Review
            </button>
          </div>
        </div>
      </div>

      {/* Save Title Input */}
      <div className="max-w-full md:max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-4 sm:py-6">
        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-4 sm:p-6">
          <label className="block text-xs sm:text-sm text-gray-400 mb-2">Review Title (optional)</label>
          <input
            type="text"
            value={reviewTitle}
            onChange={(e) => setReviewTitle(e.target.value)}
            placeholder="e.g. Transformer Models in Healthcare - March 2026"
            className="w-full bg-gray-950 border border-gray-700 rounded-xl px-4 sm:px-5 py-2 sm:py-3 text-white text-sm sm:text-base focus:outline-none focus:border-teal-500"
          />
        </div>
      </div>

      <div className="max-w-full md:max-w-6xl mx-auto px-4 sm:px-6 md:px-8">
        {data.results.map((result, index) => {
          const filename = result.filename;
          const activeTab = getActiveTab(filename);
          const metrics = calculateMetrics(
            result.abstractive_summary || "", 
            result.extractive?.key_sentences?.length || 0
          );
          const themes = themesData[filename] || [];
          const isLoadingThemes = loadingThemes[filename] || false;

          return (
            <div key={index} className="mb-8 sm:mb-12 bg-gray-900 border border-gray-800 rounded-2xl sm:rounded-3xl overflow-hidden">
              {/* File Header */}
              <div className="bg-gray-950 px-4 sm:px-6 md:px-8 py-4 sm:py-5 border-b border-gray-800 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 sm:gap-4">
                <div className="flex items-center gap-2 sm:gap-4 min-w-0">
                  <div className="text-2xl sm:text-3xl flex-shrink-0">📄</div>
                  <div className="min-w-0">
                    <h3 className="font-semibold text-lg sm:text-xl truncate">{filename}</h3>
                    {result.error && <p className="text-red-400 text-xs sm:text-sm mt-1">{result.error}</p>}
                  </div>
                </div>
                <div className="text-xs sm:text-sm text-gray-400 flex-shrink-0">
                  {result.extractive?.total_extracted || 0} key sentences extracted
                </div>
              </div>

              {/* Tabs */}
              <div className="flex border-b border-gray-800 overflow-x-auto">
                <button
                  onClick={() => setActiveTab(filename, 'summary')}
                  className={`flex-1 py-3 sm:py-4 font-medium transition text-xs sm:text-sm md:text-base whitespace-nowrap ${
                    activeTab === 'summary' ? 'text-teal-400 border-b-2 border-teal-400' : 'text-gray-400 hover:text-white'
                  }`}
                >
                  Abstractive Summary (BART)
                </button>
                <button
                  onClick={() => setActiveTab(filename, 'extractive')}
                  className={`flex-1 py-3 sm:py-4 font-medium transition text-xs sm:text-sm md:text-base whitespace-nowrap ${
                    activeTab === 'extractive' ? 'text-teal-400 border-b-2 border-teal-400' : 'text-gray-400 hover:text-white'
                  }`}
                >
                  Extractive Key Sentences (TextRank)
                </button>
              </div>

              {/* Metrics Display */}
              <div className="bg-gray-950 border-b border-gray-800 px-4 sm:px-6 md:px-8 py-3 sm:py-4">
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-2 sm:gap-3 md:gap-4">
                  <div className="bg-gray-900 rounded-lg p-2 sm:p-3">
                    <p className="text-xs text-gray-400">ROUGE-1</p>
                    <p className="text-base sm:text-lg font-semibold text-teal-400">{metrics.rouge1}</p>
                  </div>
                  <div className="bg-gray-900 rounded-lg p-2 sm:p-3">
                    <p className="text-xs text-gray-400">ROUGE-2</p>
                    <p className="text-base sm:text-lg font-semibold text-teal-400">{metrics.rouge2}</p>
                  </div>
                  <div className="bg-gray-900 rounded-lg p-2 sm:p-3">
                    <p className="text-xs text-gray-400">ROUGE-L</p>
                    <p className="text-base sm:text-lg font-semibold text-teal-400">{metrics.rougeL}</p>
                  </div>
                  <div className="bg-gray-900 rounded-lg p-2 sm:p-3">
                    <p className="text-xs text-gray-400">Summary Length</p>
                    <p className="text-base sm:text-lg font-semibold text-purple-400">{metrics.summaryLength} words</p>
                  </div>
                  <div className="bg-gray-900 rounded-lg p-2 sm:p-3">
                    <p className="text-xs text-gray-400">Compression</p>
                    <p className="text-base sm:text-lg font-semibold text-blue-400">{metrics.compressionRatio}%</p>
                  </div>
                </div>
              </div>

              {/* Content Area */}
              <div 
                className="p-4 sm:p-6 md:p-8"
                data-export={filename}
              >
                {activeTab === 'summary' ? (
                  <div className="space-y-4 sm:space-y-6">
                    {/* Summary Section */}
                    <div className="relative">
                      <button
                        onClick={() => copyToClipboard(result.abstractive_summary || "", `summary-${filename}`)}
                        className="absolute top-2 right-2 text-teal-400 hover:text-teal-300 flex items-center gap-1 sm:gap-2 px-2 sm:px-3 py-1 sm:py-2 rounded-lg hover:bg-gray-800 transition-all text-xs sm:text-sm"
                        title={copiedId === `summary-${filename}` ? "Copied!" : "Copy summary"}
                      >
                        {copiedId === `summary-${filename}` ? (
                          <Check size={16} className="text-green-400" />
                        ) : (
                          <Copy size={16} />
                        )}
                        <span className="hidden sm:inline">Copy</span>
                      </button>
                      <p className="text-base sm:text-lg text-gray-200 leading-relaxed pr-12 sm:pr-24">
                        {result.abstractive_summary || "No summary available."}
                      </p>
                    </div>

                    {/* Key Themes Section */}
                    {isLoadingThemes ? (
                      <div>
                        <h4 className="text-xs sm:text-sm font-semibold text-gray-400 mb-2 sm:mb-3">Key Themes</h4>
                        <div className="flex gap-2">
                          {[1, 2, 3].map((i) => (
                            <div key={i} className="h-6 sm:h-7 w-16 sm:w-20 bg-gray-800 rounded-full animate-pulse"></div>
                          ))}
                        </div>
                      </div>
                    ) : themes.length > 0 ? (
                      <div>
                        <h4 className="text-xs sm:text-sm font-semibold text-gray-400 mb-2 sm:mb-3">Key Themes</h4>
                        <div className="flex flex-wrap gap-2">
                          {themes.map((theme, i) => (
                            <span
                              key={i}
                              className="px-2.5 sm:px-3 py-1 sm:py-1.5 bg-teal-900/40 text-teal-300 text-xs sm:text-sm rounded-full border border-teal-700/50 hover:bg-teal-900/60 transition"
                            >
                              #{theme}
                            </span>
                          ))}
                        </div>
                      </div>
                    ) : null}
                  </div>
                ) : (
                  <div className="space-y-3 sm:space-y-6">
                    {result.extractive?.key_sentences?.map((sentence, i) => (
                      <div key={i} className="flex gap-3 sm:gap-5 bg-gray-950 p-3 sm:p-4 md:p-6 rounded-lg sm:rounded-2xl border border-gray-800 group">
                        <div className="w-7 sm:w-8 h-7 sm:h-8 rounded-full bg-teal-900 flex-shrink-0 flex items-center justify-center font-bold text-xs sm:text-sm">
                          {i + 1}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-sm sm:text-base text-gray-200 leading-relaxed">
                            {sentence.sentence}
                          </p>
                          <div className="mt-2 sm:mt-3 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 sm:gap-0">
                            <div className="flex gap-2 sm:gap-4 text-xs text-gray-500 flex-wrap">
                              <span>Score: <span className="text-teal-400">{sentence.score.toFixed(3)}</span></span>
                              <span>Rank: <span className="text-teal-400">#{sentence.rank}</span></span>
                              <span>Position: <span className="text-teal-400">{sentence.original_position}</span></span>
                            </div>
                            <button
                              onClick={() => copyToClipboard(sentence.sentence, `sent-${filename}-${i}`)}
                              className="text-teal-400 hover:text-teal-300 inline-flex items-center gap-1 px-2 sm:px-3 py-1 sm:py-1.5 rounded-lg hover:bg-gray-800 transition-all text-xs sm:text-sm whitespace-nowrap"
                              title={copiedId === `sent-${filename}-${i}` ? "Copied!" : "Copy sentence"}
                            >
                              {copiedId === `sent-${filename}-${i}` ? (
                                <Check size={14} className="text-green-400" />
                              ) : (
                                <Copy size={14} />
                              )}
                              <span className="hidden sm:inline">Copy</span>
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Export Buttons */}
              <div className="bg-gray-950 border-t border-gray-800 px-4 sm:px-6 md:px-8 py-3 sm:py-4 flex flex-col sm:flex-row gap-2 sm:gap-3">
                <button
                  onClick={() => copyAllResults(result)}
                  className="flex items-center justify-center sm:justify-start gap-2 px-3 sm:px-4 py-2 sm:py-2.5 bg-gray-800 hover:bg-gray-700 rounded-lg transition text-xs sm:text-sm font-medium text-gray-300 flex-1 sm:flex-none"
                  title="Copy both summary and all key sentences"
                >
                  <Copy size={16} />
                  <span>Copy All</span>
                </button>
                <button
                  onClick={() => exportAsText(filename, result.abstractive_summary || "", result.extractive?.key_sentences || [])}
                  className="flex items-center justify-center sm:justify-start gap-2 px-3 sm:px-4 py-2 sm:py-2.5 bg-gray-800 hover:bg-gray-700 rounded-lg transition text-xs sm:text-sm font-medium text-gray-300 flex-1 sm:flex-none"
                  title="Export as text file"
                >
                  <FileText size={16} />
                  <span>Export TXT</span>
                </button>
                <button
                  onClick={() => exportAsPDF(filename)}
                  className="flex items-center justify-center sm:justify-start gap-2 px-3 sm:px-4 py-2 sm:py-2.5 bg-teal-700 hover:bg-teal-600 rounded-lg transition text-xs sm:text-sm font-medium text-white flex-1 sm:flex-none"
                  title="Export as PDF"
                >
                  <Download size={16} />
                  <span>Export PDF</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Footer */}
      <div className="text-center text-gray-500 text-sm mt-16">
        Hybrid TextRank + BART Pipeline • Deji Ayodeji • Covenant University FYP 2025/2026
      </div>
    </div>
  );
}