import type { KeySentence } from '../types';

export const exportAsText = (filename: string, summary: string, sentences: KeySentence[]) => {
  const content = `
LITERATURE REVIEW EXPORT
=======================
Document: ${filename}
Exported: ${new Date().toLocaleString()}

ABSTRACTIVE SUMMARY (BART)
--------------------------
${summary}

KEY SENTENCES (TextRank)
------------------------
${sentences.map((sentence, index) => `${index + 1}. ${sentence.sentence}\n   Score: ${sentence.score.toFixed(3)}`).join('\n\n')}

---
Generated by Automated Literature Review Assistant
`;

  const element = document.createElement('a');
  element.setAttribute('href', `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`);
  element.setAttribute('download', `${filename.replace(/\.[^/.]+$/, '')}_review.txt`);
  element.style.display = 'none';
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};

export const exportAsPDF = (filename: string) => {
  const printWindow = window.open('', '', 'height=600,width=800');
  if (!printWindow) return;

  const content = document.querySelector(`[data-export="${filename}"]`)?.innerHTML || '';
  printWindow.document.write(`
    <html>
      <head>
        <title>${filename} - Literature Review</title>
        <style>
          body { font-family: Arial, sans-serif; color: #333; margin: 40px; }
          h1 { color: #0d9488; border-bottom: 2px solid #0d9488; padding-bottom: 10px; }
          h2 { color: #0f766e; margin-top: 30px; }
          .summary { background: #f0fdf4; padding: 15px; border-radius: 8px; margin: 20px 0; }
          .sentence { background: #f3f4f6; padding: 12px; margin: 10px 0; border-left: 4px solid #0d9488; }
          .metrics { background: #f9fafb; padding: 15px; border-radius: 8px; margin: 20px 0; }
          .metric-item { display: inline-block; margin-right: 20px; }
          .footer { margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          Generated by Automated Literature Review Assistant - Hybrid TextRank + BART Pipeline
        </div>
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.print();
};
